# -*- coding: utf-8 -*-
"""gerador_dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y-SPsU_Bpcy8-7cxe_1DDAyTtmV77o-c
"""

import random

aleatorios = [random.randint(0, 100) for i in range(50)]

dados = "exemplo2.txt"

with open(dados, 'w') as dados:
    for num in aleatorios:
        dados.write(str(num) + '\n')