# -*- coding: utf-8 -*-
"""script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GsXEPGj7kSSjW4s8GkHhgp0kd0Jxf5XQ
"""

import datetime

def intervalos(lista):
  intervalos = []
  inicio_intervalo = None

  for i, valor in enumerate(lista):
    if valor >= 50:
      if inicio_intervalo is None:
        inicio_intervalo = i
    elif inicio_intervalo is not None:
      intervalos.append((inicio_intervalo, i - 1))
      inicio_intervalo = None

  if inicio_intervalo is not None:
    intervalos.append((inicio_intervalo, len(lista) - 1))

  return intervalos

def imprimir_picos_verdadeiros(lista, intervalos):
    for i, (inicio, fim) in enumerate(intervalos):
        maximo = max(lista[inicio:fim + 1])
        print(f"Pico {i+1}: {maximo}")

def tempo_medio_picos(lista, intervalos):
  tempos = []
  for inicio, fim in intervalos:
    sublista = lista[inicio:fim + 1]
    maximo = max(sublista)
    indice_real = inicio + sublista.index(maximo)
    tempos.append(indice_real)

  diferencas = [tempos[i+1] - tempos[i] for i in range(len(tempos)-1)]
  media_segundos = sum(diferencas) / len(diferencas)

  td = datetime.timedelta(seconds=media_segundos)
  h, m, s = str(td).split(":")
  if h == "0":
      return "{}:{}".format(m, s)
  return str(td)

def ler_dados(dados):
  with open(dados, 'r') as dados:
    linhas = dados.readlines()
  lista = [int(linha.strip()) for linha in linhas]
  return lista

#TESTE
#obtendo os dados
dados = 'exemplo.txt'
lista = ler_dados(dados)
print("Lista:", lista)

#encontrando os intervalos
intervalos = intervalos(lista)

#imprimindo os picos verdadeiros
imprimir_picos_verdadeiros(lista, intervalos)

#imprimindo o tempo médio entre os picos
print("Tempo médio entre os picos:", tempo_medio_picos(lista, intervalos))